# Generated by Django 6.0.3 on 2026-03-12 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dmis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControllerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('controller_type', models.CharField(choices=[('test', 'Test Controller'), ('fanuc', 'Fanuc'), ('siemens', 'Siemens'), ('haas', 'Haas'), ('other', 'Other')], max_length=20)),
                ('port', models.CharField(blank=True, help_text='e.g., COM3 or /dev/ttyUSB0', max_length=50)),
                ('baudrate', models.IntegerField(default=9600)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Controller Configuration',
                'verbose_name_plural': 'Controller Configurations',
            },
        ),
        migrations.CreateModel(
            name='GaugeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('dll_path', models.CharField(blank=True, max_length=500)),
                ('use_64bit', models.BooleanField(default=True)),
                ('polling_rate_hz', models.FloatField(default=10.0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gauge Configuration',
                'verbose_name_plural': 'Gauge Configurations',
            },
        ),
        migrations.CreateModel(
            name='ChannelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_index', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('enabled', models.BooleanField(default=True)),
                ('feature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channels', to='dmis.feature')),
                ('gauge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='devices.gaugeconfig')),
            ],
            options={
                'verbose_name': 'Channel Configuration',
                'verbose_name_plural': 'Channel Configurations',
                'unique_together': {('gauge', 'channel_index')},
            },
        ),
        migrations.CreateModel(
            name='ToolMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_number', models.IntegerField()),
                ('offset_multiplier', models.FloatField(default=-1.0, help_text='Multiplier for deviation. -1 = compensate')),
                ('enabled', models.BooleanField(default=True)),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_mappings', to='devices.controllerconfig')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_mappings', to='dmis.feature')),
            ],
            options={
                'verbose_name': 'Tool Mapping',
                'verbose_name_plural': 'Tool Mappings',
                'unique_together': {('controller', 'feature')},
            },
        ),
    ]
