# Generated by Django 6.0.3 on 2026-03-12 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Tsugami Swiss #3', 'Grinding Cell 1'", max_length=100)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, help_text="e.g., 'Building A, Line 2'", max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Active machine is shown on dashboard')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Machine',
                'verbose_name_plural': 'Machines',
            },
        ),
        migrations.AlterModelOptions(
            name='channelconfig',
            options={'ordering': ['gauge', 'channel_index'], 'verbose_name': 'Channel Configuration', 'verbose_name_plural': 'Channel Configurations'},
        ),
        migrations.RemoveField(
            model_name='channelconfig',
            name='feature',
        ),
        migrations.RemoveField(
            model_name='controllerconfig',
            name='baudrate',
        ),
        migrations.RemoveField(
            model_name='gaugeconfig',
            name='polling_rate_hz',
        ),
        migrations.AddField(
            model_name='controllerconfig',
            name='host',
            field=models.CharField(blank=True, help_text='IP address for network controllers (e.g., 192.168.1.100)', max_length=100),
        ),
        migrations.AddField(
            model_name='gaugeconfig',
            name='filter_level',
            field=models.IntegerField(choices=[(0, 'Off (Raw)'), (1, '2 samples'), (2, '4 samples'), (3, '8 samples'), (4, '16 samples'), (5, '32 samples'), (6, '64 samples')], default=5, help_text='Digital averaging filter level'),
        ),
        migrations.AddField(
            model_name='toolmapping',
            name='offset_register',
            field=models.CharField(blank=True, help_text="Offset register if different from tool (e.g., 'D01', 'H01')", max_length=20),
        ),
        migrations.AlterField(
            model_name='channelconfig',
            name='channel_index',
            field=models.IntegerField(help_text='0-based channel index (matches DLL)'),
        ),
        migrations.AlterField(
            model_name='channelconfig',
            name='name',
            field=models.CharField(help_text="Friendly name, e.g., 'OD Probe Left'", max_length=100),
        ),
        migrations.AlterField(
            model_name='controllerconfig',
            name='controller_type',
            field=models.CharField(choices=[('test', 'Test Controller'), ('fanuc', 'Fanuc (FOCAS)'), ('siemens', 'Siemens'), ('haas', 'Haas'), ('mazak', 'Mazak'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='controllerconfig',
            name='port',
            field=models.CharField(blank=True, help_text='Port number or serial port (e.g., 8193 or COM3)', max_length=50),
        ),
        migrations.AlterField(
            model_name='toolmapping',
            name='offset_multiplier',
            field=models.FloatField(default=-1.0, help_text='Multiplier for deviation. -1 = compensate (most common)'),
        ),
        migrations.AlterField(
            model_name='toolmapping',
            name='tool_number',
            field=models.IntegerField(help_text='Tool number in CNC (e.g., 1 for T01)'),
        ),
        migrations.AddField(
            model_name='controllerconfig',
            name='machine',
            field=models.ForeignKey(blank=True, help_text='Machine this controller belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='controllers', to='devices.machine'),
        ),
        migrations.AddField(
            model_name='gaugeconfig',
            name='machine',
            field=models.ForeignKey(blank=True, help_text='Machine this gauge belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gauges', to='devices.machine'),
        ),
    ]
