# Generated by Django 6.0.3 on 2026-03-12 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_machine_alter_channelconfig_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gaugeconfig',
            name='driver_type',
            field=models.CharField(choices=[('n1700', 'Mahr Millimar N1700')], default='n1700', help_text='Gauge driver/hardware type', max_length=20),
        ),
    ]
