# Generated by Django 6.0.3 on 2026-03-12 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_gaugeconfig_driver_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelconfig',
            name='channel_index',
            field=models.PositiveIntegerField(help_text='0-based channel index (matches hardware)'),
        ),
    ]
