# Generated by Django 6.0.3 on 2026-03-13 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('controller', '0001_initial'),
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompensationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_number', models.IntegerField(help_text='Tool number in CNC (e.g., 1 for T01)')),
                ('offset_register', models.CharField(blank=True, help_text="Offset register if different from tool (e.g., 'D01', 'H01')", max_length=20)),
                ('offset_axis', models.CharField(choices=[('X', 'X'), ('Y', 'Y'), ('Z', 'Z')], default='X', help_text='Axis this tool cuts on', max_length=1)),
                ('offset_direction', models.FloatField(default=-1.0, help_text='Multiplier: -1 = compensate (most common), +1 = amplify')),
                ('trigger_mode', models.CharField(choices=[('THR', 'Threshold (compensate when deviation exceeds)'), ('ALL', 'Every Cycle (always compensate)'), ('AVG', 'Average N samples before compensating')], default='THR', help_text='When to trigger compensation', max_length=3)),
                ('trigger_threshold', models.FloatField(default=0.005, help_text='Compensate when |deviation| exceeds this (for THRESHOLD mode)')),
                ('sample_count', models.IntegerField(default=1, help_text='Number of samples to average (for AVG mode)')),
                ('max_per_cycle', models.FloatField(default=0.01, help_text='Maximum offset change per cycle (safety cap)')),
                ('wear_limit', models.FloatField(default=0.05, help_text='Alert/stop when accumulated offset reaches this')),
                ('wear_limit_action', models.CharField(choices=[('ALERT', 'Alert operator'), ('STOP', 'Stop compensation'), ('TOOL', 'Request tool change')], default='ALERT', help_text='Action when wear limit is reached', max_length=5)),
                ('active', models.BooleanField(default=True, help_text='Enable/disable this compensation rule')),
                ('accumulated_offset', models.FloatField(default=0, help_text='Running total of all offset adjustments')),
                ('last_adjustment', models.FloatField(default=0, help_text='Most recent offset adjustment')),
                ('last_adjustment_at', models.DateTimeField(blank=True, help_text='When last adjustment was made', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('controller', models.ForeignKey(help_text='Controller to send offset adjustments', on_delete=django.db.models.deletion.CASCADE, related_name='compensation_rules', to='controller.controllerconfig')),
                ('feature', models.ForeignKey(help_text='Feature to monitor for compensation', on_delete=django.db.models.deletion.CASCADE, related_name='compensation_rules', to='measurement.feature')),
            ],
            options={
                'verbose_name': 'Compensation Rule',
                'verbose_name_plural': 'Compensation Rules',
                'ordering': ['feature__name', 'tool_number'],
                'unique_together': {('feature', 'controller', 'tool_number')},
            },
        ),
        migrations.CreateModel(
            name='CompensationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviation_in', models.FloatField(help_text='Deviation from measurement')),
                ('offset_calculated', models.FloatField(help_text='Raw offset before safety clamps')),
                ('offset_applied', models.FloatField(help_text='Actual offset sent to controller')),
                ('accumulated_before', models.FloatField(help_text='Accumulated offset before this event')),
                ('accumulated_after', models.FloatField(help_text='Accumulated offset after this event')),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('SKIPPED', 'Skipped (below threshold)'), ('CLAMPED', 'Clamped (exceeded max per cycle)'), ('BLOCKED', 'Blocked (wear limit reached)'), ('ERROR', 'Error')], help_text='What happened', max_length=10)),
                ('reason', models.CharField(blank=True, help_text='Explanation of decision', max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensation_events', to='measurement.measurement')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='compensation.compensationrule')),
            ],
            options={
                'verbose_name': 'Compensation Event',
                'verbose_name_plural': 'Compensation Events',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['rule', 'timestamp'], name='compensatio_rule_id_65bd4c_idx'), models.Index(fields=['timestamp'], name='compensatio_timesta_aab925_idx')],
            },
        ),
    ]
