# Generated by Django 6.0.3 on 2026-04-16 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compensation', '0001_initial'),
        ('controller', '0001_initial'),
        ('tooling', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compensationrule',
            options={'ordering': ['feature__name'], 'verbose_name': 'Compensation Rule', 'verbose_name_plural': 'Compensation Rules'},
        ),
        migrations.AlterUniqueTogether(
            name='compensationrule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='compensationrule',
            name='tool_assignment',
            field=models.ForeignKey(blank=True, help_text='Tool assignment to send offsets to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compensation_rules', to='tooling.toolassignment'),
        ),
        migrations.AddField(
            model_name='compensationrule',
            name='warning_threshold',
            field=models.FloatField(default=0.8, help_text='Warn when accumulated offset reaches this fraction of tool limit (0.0-1.0)'),
        ),
        migrations.AlterField(
            model_name='compensationrule',
            name='accumulated_offset',
            field=models.FloatField(blank=True, default=0, help_text='DEPRECATED - use ToolAssignment.accumulated_offset', null=True),
        ),
        migrations.AlterField(
            model_name='compensationrule',
            name='controller',
            field=models.ForeignKey(blank=True, help_text='DEPRECATED - use tool_assignment', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compensation_rules', to='controller.controllerconfig'),
        ),
        migrations.AlterField(
            model_name='compensationrule',
            name='last_adjustment',
            field=models.FloatField(blank=True, default=0, help_text='DEPRECATED', null=True),
        ),
        migrations.AlterField(
            model_name='compensationrule',
            name='last_adjustment_at',
            field=models.DateTimeField(blank=True, help_text='DEPRECATED', null=True),
        ),
        migrations.AlterField(
            model_name='compensationrule',
            name='tool_number',
            field=models.IntegerField(blank=True, help_text='DEPRECATED - use tool_assignment', null=True),
        ),
        migrations.AlterField(
            model_name='compensationrule',
            name='wear_limit',
            field=models.FloatField(blank=True, default=0.05, help_text='DEPRECATED - use Tool.max_offset_distance', null=True),
        ),
    ]
