# Generated by Django 6.0.3 on 2026-04-17 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compensation', '0002_alter_compensationrule_options_and_more'),
        ('tooling', '0002_toolinstance_tooltype_remove_toolassignment_tool_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compensationrule',
            name='accumulated_offset',
        ),
        migrations.RemoveField(
            model_name='compensationrule',
            name='controller',
        ),
        migrations.RemoveField(
            model_name='compensationrule',
            name='last_adjustment',
        ),
        migrations.RemoveField(
            model_name='compensationrule',
            name='last_adjustment_at',
        ),
        migrations.RemoveField(
            model_name='compensationrule',
            name='tool_number',
        ),
        migrations.RemoveField(
            model_name='compensationrule',
            name='wear_limit',
        ),
        migrations.AlterField(
            model_name='compensationrule',
            name='tool_assignment',
            field=models.ForeignKey(default=1, help_text='Tool assignment to send offsets to', on_delete=django.db.models.deletion.CASCADE, related_name='compensation_rules', to='tooling.toolassignment'),
            preserve_default=False,
        ),
    ]
