# Generated by Django 6.0.3 on 2026-04-16 16:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('controller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for tracking and reporting', unique=True)),
                ('name', models.CharField(help_text="Tool identifier (e.g., 'CNMG 120408', 'OD Roughing Insert')", max_length=100)),
                ('manufacturer', models.CharField(blank=True, help_text="Tool manufacturer (e.g., 'Sandvik', 'Kennametal')", max_length=100)),
                ('part_number', models.CharField(blank=True, help_text='Manufacturer part number', max_length=100)),
                ('max_offset_distance', models.FloatField(default=0.1, help_text='Maximum total offset allowed before tool change required (mm)')),
                ('estimated_life_cycles', models.IntegerField(blank=True, help_text='Estimated tool life in cycles/parts (optional)', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this tool')),
                ('active', models.BooleanField(default=True, help_text='Available for assignment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tool',
                'verbose_name_plural': 'Tools',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ToolAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this specific installation instance', unique=True)),
                ('tool_position', models.IntegerField(help_text='Tool position number (e.g., 1 for T1)')),
                ('installed_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this tool was installed')),
                ('removed_at', models.DateTimeField(blank=True, help_text='When this tool was replaced (null if still active)', null=True)),
                ('accumulated_offset', models.FloatField(default=0.0, help_text='Total offset applied since installation')),
                ('cycle_count', models.IntegerField(default=0, help_text='Number of cycles since installation')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('WARNING', 'Warning (approaching limit)'), ('CHANGE', 'Change Required'), ('REPLACED', 'Replaced')], default='ACTIVE', help_text='Current status of this assignment', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('controller', models.ForeignKey(help_text='Machine/controller this tool is installed on', on_delete=django.db.models.deletion.CASCADE, related_name='tool_assignments', to='controller.controllerconfig')),
                ('tool', models.ForeignKey(help_text='Tool type installed', on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='tooling.tool')),
            ],
            options={
                'verbose_name': 'Tool Assignment',
                'verbose_name_plural': 'Tool Assignments',
                'ordering': ['-installed_at'],
                'indexes': [models.Index(fields=['controller', 'tool_position', 'status'], name='tooling_too_control_3083a6_idx'), models.Index(fields=['status'], name='tooling_too_status_33c278_idx')],
            },
        ),
    ]
