# Generated by Django 6.0.3 on 2026-04-16 19:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tooling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this specific physical tool', unique=True)),
                ('total_parts_cut', models.IntegerField(default=0, help_text='Total parts cut by this instance (lifetime)')),
                ('total_accumulated_wear', models.FloatField(default=0.0, help_text='Total offset applied to this instance (lifetime)')),
                ('status', models.CharField(choices=[('IN_USE', 'In Use'), ('NOT_IN_USE', 'Not In Use')], default='IN_USE', help_text='Current status of this instance', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tool Instance',
                'verbose_name_plural': 'Tool Instances',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ToolType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for tracking and reporting', unique=True)),
                ('name', models.CharField(help_text="Tool identifier (e.g., 'CNMG 120408', 'OD Roughing Insert')", max_length=100)),
                ('manufacturer', models.CharField(blank=True, help_text="Tool manufacturer (e.g., 'Sandvik', 'Kennametal')", max_length=100)),
                ('part_number', models.CharField(blank=True, help_text='Manufacturer part number', max_length=100)),
                ('tool_kind', models.CharField(blank=True, help_text="Type of tool (e.g., 'insert', 'boring_bar', 'drill', 'end_mill')", max_length=50)),
                ('max_offset_distance', models.FloatField(default=0.1, help_text='Maximum total offset allowed before tool change required (mm)')),
                ('avg_parts_per_instance', models.FloatField(default=0.0, help_text='Average parts cut per instance (calculated from retired instances)')),
                ('instance_count', models.IntegerField(default=0, help_text='Total number of instances used (for calculating average)')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this tool type')),
                ('active', models.BooleanField(default=True, help_text='Available for new instances')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tool Type',
                'verbose_name_plural': 'Tool Types',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='toolassignment',
            name='tool',
        ),
        migrations.AlterField(
            model_name='toolassignment',
            name='accumulated_offset',
            field=models.FloatField(default=0.0, help_text='Total offset applied this session'),
        ),
        migrations.AlterField(
            model_name='toolassignment',
            name='cycle_count',
            field=models.IntegerField(default=0, help_text='Number of cycles this session'),
        ),
        migrations.AlterField(
            model_name='toolassignment',
            name='removed_at',
            field=models.DateTimeField(blank=True, help_text='When this tool was removed (null if still active)', null=True),
        ),
        migrations.AlterField(
            model_name='toolassignment',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this specific installation session', unique=True),
        ),
        migrations.AddField(
            model_name='toolassignment',
            name='tool_instance',
            field=models.ForeignKey(default=1, help_text='Specific tool instance installed', on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='tooling.toolinstance'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='toolinstance',
            name='tool_type',
            field=models.ForeignKey(help_text='Type of tool this instance is', on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='tooling.tooltype'),
        ),
        migrations.DeleteModel(
            name='Tool',
        ),
    ]
