# Generated by Django 6.0.3 on 2026-03-13 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Tsugami Swiss #3', 'Grinding Cell 1'", max_length=100)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, help_text="e.g., 'Building A, Line 2'", max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Active machine is shown on dashboard')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Machine',
                'verbose_name_plural': 'Machines',
            },
        ),
        migrations.CreateModel(
            name='ControllerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Tsugami B0205 Main'", max_length=100, unique=True)),
                ('controller_type', models.CharField(choices=[('fanuc', 'Fanuc'), ('siemens', 'Siemens'), ('haas', 'Haas'), ('mazak', 'Mazak'), ('mitsubishi', 'Mitsubishi'), ('okuma', 'Okuma'), ('brother', 'Brother'), ('citizen', 'Citizen'), ('tsugami', 'Tsugami'), ('star', 'Star'), ('other', 'Other'), ('test', 'Test/Simulator')], help_text='CNC manufacturer/type', max_length=20)),
                ('protocol', models.CharField(choices=[('FOCAS2', 'Fanuc FOCAS2'), ('MTC', 'MTConnect'), ('OPC', 'OPC-UA'), ('MOD', 'Modbus TCP'), ('TEST', 'Test/Simulator')], default='FOCAS2', help_text='Communication protocol', max_length=10)),
                ('host', models.CharField(blank=True, help_text='IP address (e.g., 192.168.1.100)', max_length=100)),
                ('port', models.IntegerField(default=8193, help_text='Port number (FOCAS default: 8193)')),
                ('timeout_ms', models.IntegerField(default=1000, help_text='Connection timeout in milliseconds')),
                ('signal_cycle_complete', models.CharField(blank=True, help_text='PLC address for cycle complete (e.g., R100.0)', max_length=50)),
                ('signal_master_request', models.CharField(blank=True, help_text='PLC address for master/zero request', max_length=50)),
                ('signal_part_present', models.CharField(blank=True, help_text='PLC address for part-in-fixture sensor', max_length=50)),
                ('signal_tool_change', models.CharField(blank=True, help_text='PLC address for tool change notification', max_length=50)),
                ('signal_ready', models.CharField(blank=True, help_text='PLC address to signal measurement complete', max_length=50)),
                ('signal_alarm', models.CharField(blank=True, help_text='PLC address to signal alarm/fault', max_length=50)),
                ('signal_measuring', models.CharField(blank=True, help_text='PLC address to signal measurement in progress', max_length=50)),
                ('signal_pass', models.CharField(blank=True, help_text='PLC address to signal part passed', max_length=50)),
                ('signal_fail', models.CharField(blank=True, help_text='PLC address to signal part failed', max_length=50)),
                ('offset_method', models.CharField(choices=[('WEAR', 'Wear Offset'), ('GEOM', 'Geometry Offset'), ('MACRO', 'Macro Variable')], default='WEAR', help_text='How offsets are written to CNC', max_length=5)),
                ('offset_resolution', models.FloatField(default=0.001, help_text='Minimum offset increment CNC accepts (mm)')),
                ('offset_write_delay_ms', models.IntegerField(default=50, help_text='Delay after writing offset before next operation')),
                ('active', models.BooleanField(default=True, help_text='Enable/disable this controller')),
                ('connected', models.BooleanField(default=False, help_text='Current connection status (runtime)')),
                ('last_heartbeat', models.DateTimeField(blank=True, help_text='Last successful communication', null=True)),
                ('last_error', models.CharField(blank=True, help_text='Last error message', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machine', models.ForeignKey(blank=True, help_text='Machine this controller belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='controllers', to='controller.machine')),
            ],
            options={
                'verbose_name': 'Controller Configuration',
                'verbose_name_plural': 'Controller Configurations',
                'ordering': ['name'],
            },
        ),
    ]
