# Generated by Django 6.0.3 on 2026-04-16 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='controllerconfig',
            name='on_tool_limit',
            field=models.CharField(choices=[('ALARM', 'Alarm (stop machine)'), ('WARNING', 'Warning only (keep running)')], default='ALARM', help_text='Action when tool reaches compensation limit (offsets are always blocked)', max_length=10),
        ),
    ]
