# Generated by Django 6.0.3 on 2026-03-12 06:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('feature_type', models.CharField(choices=[('CIRCLE', 'Circle'), ('CYLINDER', 'Cylinder'), ('PLANE', 'Plane'), ('LINE', 'Line'), ('POINT', 'Point'), ('CONE', 'Cone'), ('SPHERE', 'Sphere')], max_length=20)),
                ('nominal', models.FloatField(help_text='Target value')),
                ('unit', models.CharField(choices=[('mm', 'Millimeters'), ('inch', 'Inches')], default='mm', max_length=10)),
                ('x', models.FloatField(blank=True, null=True)),
                ('y', models.FloatField(blank=True, null=True)),
                ('z', models.FloatField(blank=True, null=True)),
                ('part_name', models.CharField(blank=True, max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual', models.FloatField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', models.CharField(blank=True, help_text='Gauge/channel that took reading', max_length=100)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='dmis.feature')),
            ],
            options={
                'verbose_name': 'Measurement',
                'verbose_name_plural': 'Measurements',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Offset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('controller', models.CharField(max_length=100)),
                ('tool_number', models.IntegerField()),
                ('offset_value', models.FloatField()),
                ('applied', models.BooleanField(default=False)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('measurement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offset', to='dmis.measurement')),
            ],
            options={
                'verbose_name': 'Offset',
                'verbose_name_plural': 'Offsets',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='Tolerance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upper', models.FloatField(help_text='Upper deviation limit')),
                ('lower', models.FloatField(help_text='Lower deviation limit')),
                ('feature', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tolerance', to='dmis.feature')),
            ],
            options={
                'verbose_name': 'Tolerance',
                'verbose_name_plural': 'Tolerances',
            },
        ),
    ]
