# Generated by Django 6.0.3 on 2026-03-12 19:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('feature_type', models.CharField(choices=[('DIA', 'Diameter'), ('RAD', 'Radius'), ('LEN', 'Length'), ('POS', 'Position'), ('TIR', 'TIR (Total Indicator Reading)'), ('RUN', 'Runout'), ('FLT', 'Flatness'), ('PER', 'Perpendicularity'), ('PAR', 'Parallelism'), ('CON', 'Concentricity'), ('TAP', 'Taper'), ('DEV', 'Deviation (Generic)')], default='DEV', max_length=3)),
                ('part_name', models.CharField(blank=True, max_length=100)),
                ('part_number', models.CharField(blank=True, max_length=100)),
                ('channel_1', models.IntegerField(help_text='Primary channel index (0-based)')),
                ('channel_2', models.IntegerField(blank=True, help_text='Secondary channel index for two-channel formulas (0-based)', null=True)),
                ('function', models.CharField(choices=[('C1', 'C1 (Channel 1 only)'), ('C2', 'C2 (Channel 2 only)'), ('SUM', 'C1 + C2 (Sum)'), ('DIFF', 'C1 − C2 (Difference)'), ('DIFF_REV', 'C2 − C1 (Reverse Difference)'), ('AVG', '(C1 + C2) / 2 (Average)'), ('ABS_DIFF', '|C1 − C2| (Absolute Difference)'), ('MAX', 'max(C1, C2) (Maximum)'), ('MIN', 'min(C1, C2) (Minimum)')], default='C1', help_text='How to combine channel values', max_length=10)),
                ('factor', models.FloatField(default=1.0, help_text='Multiplier applied to function result')),
                ('offset', models.FloatField(default=0.0, help_text='Constant added after factor multiplication')),
                ('divisor', models.FloatField(default=1.0, help_text='Divisor applied last')),
                ('tolerance_mode', models.CharField(choices=[('BI', 'Bilateral (± from nominal)'), ('UNI_P', 'Unilateral Positive (nominal to +upper)'), ('UNI_N', 'Unilateral Negative (nominal to -lower)'), ('LIM', 'Limit Only (0 to limit, e.g., TIR)')], default='BI', max_length=5)),
                ('nominal', models.FloatField(blank=True, help_text='Nominal/target value (not used for LIMIT mode)', null=True)),
                ('tolerance_upper', models.FloatField(help_text='Upper tolerance limit (or single limit for LIMIT mode)')),
                ('tolerance_lower', models.FloatField(blank=True, help_text='Lower tolerance limit (not used for LIMIT or UNILATERAL_POS mode)', null=True)),
                ('warning_upper', models.FloatField(blank=True, help_text='Upper warning limit (inside tolerance)', null=True)),
                ('warning_lower', models.FloatField(blank=True, help_text='Lower warning limit (inside tolerance)', null=True)),
                ('unit', models.CharField(choices=[('mm', 'Millimeters'), ('in', 'Inches'), ('um', 'Micrometers')], default='mm', max_length=2)),
                ('resolution', models.IntegerField(default=4, help_text='Decimal places for display')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FeatureTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('feature_type', models.CharField(choices=[('DIA', 'Diameter'), ('RAD', 'Radius'), ('LEN', 'Length'), ('POS', 'Position'), ('TIR', 'TIR (Total Indicator Reading)'), ('RUN', 'Runout'), ('FLT', 'Flatness'), ('PER', 'Perpendicularity'), ('PAR', 'Parallelism'), ('CON', 'Concentricity'), ('TAP', 'Taper'), ('DEV', 'Deviation (Generic)')], max_length=3)),
                ('function', models.CharField(choices=[('C1', 'C1 (Channel 1 only)'), ('C2', 'C2 (Channel 2 only)'), ('SUM', 'C1 + C2 (Sum)'), ('DIFF', 'C1 − C2 (Difference)'), ('DIFF_REV', 'C2 − C1 (Reverse Difference)'), ('AVG', '(C1 + C2) / 2 (Average)'), ('ABS_DIFF', '|C1 − C2| (Absolute Difference)'), ('MAX', 'max(C1, C2) (Maximum)'), ('MIN', 'min(C1, C2) (Minimum)')], default='C1', max_length=10)),
                ('factor', models.FloatField(default=1.0)),
                ('requires_two_channels', models.BooleanField(default=False)),
                ('tolerance_mode', models.CharField(choices=[('BI', 'Bilateral (± from nominal)'), ('UNI_P', 'Unilateral Positive (nominal to +upper)'), ('UNI_N', 'Unilateral Negative (nominal to -lower)'), ('LIM', 'Limit Only (0 to limit, e.g., TIR)')], default='BI', max_length=5)),
            ],
            options={
                'verbose_name': 'Feature Template',
                'verbose_name_plural': 'Feature Templates',
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_1_value', models.FloatField(help_text='Raw value from channel 1')),
                ('channel_2_value', models.FloatField(blank=True, help_text='Raw value from channel 2 (if applicable)', null=True)),
                ('computed_value', models.FloatField(help_text='Result after formula evaluation')),
                ('deviation', models.FloatField(help_text='Deviation from nominal (or value itself for LIMIT mode)')),
                ('in_tolerance', models.BooleanField()),
                ('in_warning', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=5)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', models.CharField(blank=True, help_text="Source identifier (e.g., 'N1700:CH0')", max_length=100)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='dmis.feature')),
            ],
            options={
                'verbose_name': 'Measurement',
                'verbose_name_plural': 'Measurements',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Offset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('controller', models.CharField(max_length=100)),
                ('tool_number', models.IntegerField()),
                ('offset_value', models.FloatField()),
                ('applied', models.BooleanField(default=False)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offsets', to='dmis.measurement')),
            ],
            options={
                'verbose_name': 'Offset',
                'verbose_name_plural': 'Offsets',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.AddIndex(
            model_name='measurement',
            index=models.Index(fields=['feature', 'timestamp'], name='dmis_measur_feature_7bb7f7_idx'),
        ),
        migrations.AddIndex(
            model_name='measurement',
            index=models.Index(fields=['timestamp'], name='dmis_measur_timesta_d9fed5_idx'),
        ),
    ]
