# Generated by Django 6.0.3 on 2026-03-12 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Input label (A, B, C, ... Z, AA, AB, ...)', max_length=2)),
                ('channel_index', models.PositiveIntegerField(help_text='Hardware channel index (0-based)')),
            ],
            options={
                'verbose_name': 'Feature Input',
                'verbose_name_plural': 'Feature Inputs',
                'ordering': ['feature', 'label'],
            },
        ),
        migrations.DeleteModel(
            name='FeatureTemplate',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='channel_1',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='channel_2',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='divisor',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='factor',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='function',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='offset',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='warning_lower',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='warning_upper',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='channel_1_value',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='channel_2_value',
        ),
        migrations.AddField(
            model_name='feature',
            name='formula',
            field=models.CharField(default='A', help_text="Expression using inputs A, B, C... e.g., 'A + B' or '(A - B) / 2'", max_length=200),
        ),
        migrations.AddField(
            model_name='feature',
            name='warning_percent',
            field=models.FloatField(default=80.0, help_text='Warning triggers at this percent of tolerance (0-100)'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='channel_values',
            field=models.JSONField(default=dict, help_text='Dict of channel_index: value'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='source',
            field=models.CharField(blank=True, help_text="Source identifier (e.g., 'N1700')", max_length=100),
        ),
        migrations.AddField(
            model_name='featureinput',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='dmis.feature'),
        ),
        migrations.AlterUniqueTogether(
            name='featureinput',
            unique_together={('feature', 'label')},
        ),
    ]
