# Generated by Django 6.0.3 on 2026-03-13 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmis', '0002_featureinput_delete_featuretemplate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='tolerance_upper',
            field=models.FloatField(blank=True, help_text='Upper tolerance limit (or single limit for LIMIT mode)', null=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='warning_percent',
            field=models.FloatField(blank=True, help_text='Warning triggers at this percent of tolerance (0-100)', null=True),
        ),
    ]
