# dmis/generator.py
"""
Generate DMIS-format text from Django models.
Used for traceability, export, and audit logs.
"""

from datetime import datetime
from typing import List, Optional
from .models import Feature, Measurement, Offset


def generate_header(part_name: str = "PART", units: str = "MM") -> str:
    """Generate DMIS file header."""
    timestamp = datetime.now().strftime("%Y-%m-%dT%H:%M:%S")
    return f"""DMISMN/'{part_name}',05.3
$$ Generated by KairosLoop
$$ {timestamp}
UNITS/{units}
"""


def generate_feature(feature: Feature) -> str:
    """Generate DMIS feature definition."""
    feat_type = feature.feature_type.upper()
    name = feature.name.upper().replace(" ", "_")
    
    # Basic feature with nominal
    if feat_type == "CIRCLE":
        return f"F({name})=FEAT/CIRCLE,INNER,CART,{feature.x or 0},{feature.y or 0},{feature.z or 0},{feature.nominal}"
    elif feat_type == "CYLINDER":
        return f"F({name})=FEAT/CYLNDR,INNER,CART,{feature.x or 0},{feature.y or 0},{feature.z or 0},0,0,1,{feature.nominal}"
    elif feat_type == "PLANE":
        return f"F({name})=FEAT/PLANE,CART,{feature.x or 0},{feature.y or 0},{feature.z or 0},0,0,1"
    elif feat_type == "POINT":
        return f"F({name})=FEAT/POINT,CART,{feature.x or 0},{feature.y or 0},{feature.z or 0}"
    elif feat_type == "LINE":
        return f"F({name})=FEAT/LINE,BND,CART,{feature.x or 0},{feature.y or 0},{feature.z or 0},0,1,0"
    elif feat_type == "CONE":
        return f"F({name})=FEAT/CONE,INNER,CART,{feature.x or 0},{feature.y or 0},{feature.z or 0},0,0,1,{feature.nominal},30"
    elif feat_type == "SPHERE":
        return f"F({name})=FEAT/SPHERE,INNER,CART,{feature.x or 0},{feature.y or 0},{feature.z or 0},{feature.nominal}"
    else:
        return f"$$ Unknown feature type: {feat_type}"


def generate_tolerance(feature: Feature) -> str:
    """Generate DMIS tolerance definition."""
    name = feature.name.upper().replace(" ", "_")
    try:
        tol = feature.tolerance
        return f"T({name}_TOL)=TOL/DIAM,{tol.lower},{tol.upper}"
    except Feature.tolerance.RelatedObjectDoesNotExist:
        return f"$$ No tolerance defined for {name}"


def generate_measurement(measurement: Measurement) -> str:
    """Generate DMIS measurement output."""
    name = measurement.feature.name.upper().replace(" ", "_")
    timestamp = measurement.timestamp.strftime("%Y-%m-%dT%H:%M:%S")
    
    lines = [
        f"$$ Measurement taken at {timestamp}",
        f"MEAS/DIAM,F({name}),1",
        f"  PTMEAS/CART,0,0,0,0,0,1",
        f"ENDMES",
        f"OUTPUT/FA({name}),TA({name}_TOL)",
        f"$$ Actual: {measurement.actual}, Deviation: {measurement.deviation:+.6f}",
    ]
    return "\n".join(lines)


def generate_offset_comment(offset: Offset) -> str:
    """Generate DMIS comment for tool offset applied."""
    timestamp = offset.applied_at.strftime("%Y-%m-%dT%H:%M:%S") if offset.applied_at else "pending"
    status = "APPLIED" if offset.applied else "PENDING"
    return f"$$ OFFSET T{offset.tool_number}: {offset.offset_value:+.6f} [{status}] {timestamp}"


def generate_footer() -> str:
    """Generate DMIS file footer."""
    return "ENDFIL"


def generate_full_report(
    part_name: str,
    features: List[Feature],
    measurements: Optional[List[Measurement]] = None,
    offsets: Optional[List[Offset]] = None,
    units: str = "MM"
) -> str:
    """
    Generate complete DMIS report.
    
    Usage:
        features = Feature.objects.filter(part=part)
        measurements = Measurement.objects.filter(feature__in=features)
        offsets = Offset.objects.filter(measurement__in=measurements)
        
        dmis_text = generate_full_report(
            part_name="SHAFT_001",
            features=list(features),
            measurements=list(measurements),
            offsets=list(offsets)
        )
    """
    sections = [generate_header(part_name, units)]
    
    # Features
    sections.append("$$ FEATURE DEFINITIONS")
    for feature in features:
        sections.append(generate_feature(feature))
        sections.append(generate_tolerance(feature))
    
    # Measurements
    if measurements:
        sections.append("")
        sections.append("$$ MEASUREMENTS")
        for measurement in measurements:
            sections.append(generate_measurement(measurement))
    
    # Offsets
    if offsets:
        sections.append("")
        sections.append("$$ TOOL OFFSETS")
        for offset in offsets:
            sections.append(generate_offset_comment(offset))
    
    sections.append("")
    sections.append(generate_footer())
    
    return "\n".join(sections)


# **What it does:**

# - Converts Django models → DMIS 5.3 text format
# - Generates feature definitions (CIRCLE, CYLINDER, etc.)
# - Outputs measurements with actual/deviation
# - Logs tool offsets as comments
# - Creates full audit-ready reports

# **Example output:**
# ```
# DMISMN/'SHAFT_001',05.3
# $$ Generated by KairosLoop
# $$ 2025-03-11T14:30:00
# UNITS/MM

# $$ FEATURE DEFINITIONS
# F(OD_GRIND)=FEAT/CIRCLE,INNER,CART,0,0,0,25.4
# T(OD_GRIND_TOL)=TOL/DIAM,-0.01,0.01

# $$ MEASUREMENTS
# $$ Measurement taken at 2025-03-11T14:30:00
# MEAS/DIAM,F(OD_GRIND),1
#   PTMEAS/CART,0,0,0,0,0,1
# ENDMES
# OUTPUT/FA(OD_GRIND),TA(OD_GRIND_TOL)
# $$ Actual: 25.405, Deviation: +0.005000

# $$ TOOL OFFSETS
# $$ OFFSET T1: -0.005000 [APPLIED] 2025-03-11T14:30:01

# ENDFIL