# Generated by Django 6.0.3 on 2026-03-13 15:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('controller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('feature_type', models.CharField(choices=[('DIA', 'Diameter'), ('RAD', 'Radius'), ('LEN', 'Length'), ('POS', 'Position'), ('TIR', 'TIR (Total Indicator Reading)'), ('RUN', 'Runout'), ('FLT', 'Flatness'), ('PER', 'Perpendicularity'), ('PAR', 'Parallelism'), ('CON', 'Concentricity'), ('TAP', 'Taper'), ('DEV', 'Deviation (Generic)')], default='DEV', max_length=3)),
                ('part_name', models.CharField(blank=True, max_length=100)),
                ('part_number', models.CharField(blank=True, max_length=100)),
                ('formula', models.CharField(default='A', help_text="Expression using inputs A, B, C... e.g., 'A + B' or '(A - B) / 2'", max_length=200)),
                ('tolerance_mode', models.CharField(choices=[('BI', 'Bilateral (± from nominal)'), ('UNI_P', 'Unilateral Positive (nominal to +upper)'), ('UNI_N', 'Unilateral Negative (nominal to -lower)'), ('LIM', 'Limit Only (0 to limit, e.g., TIR)')], default='BI', max_length=5)),
                ('nominal', models.FloatField(blank=True, help_text='Nominal/target value (not used for LIMIT mode)', null=True)),
                ('tolerance_upper', models.FloatField(blank=True, help_text='Upper tolerance limit (or single limit for LIMIT mode)', null=True)),
                ('tolerance_lower', models.FloatField(blank=True, help_text='Lower tolerance limit (not used for LIMIT or UNILATERAL_POS mode)', null=True)),
                ('warning_percent', models.FloatField(blank=True, help_text='Warning triggers at this percent of tolerance (0-100)', null=True)),
                ('unit', models.CharField(choices=[('mm', 'Millimeters'), ('in', 'Inches'), ('um', 'Micrometers')], default='mm', max_length=2)),
                ('resolution', models.IntegerField(default=4, help_text='Decimal places for display')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GaugeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_type', models.CharField(choices=[('n1700', 'Mahr Millimar N1700')], default='n1700', help_text='Gauge driver/hardware type', max_length=20)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('dll_path', models.CharField(blank=True, max_length=500)),
                ('use_64bit', models.BooleanField(default=True)),
                ('filter_level', models.IntegerField(choices=[(0, 'Off (Raw)'), (1, '2 samples'), (2, '4 samples'), (3, '8 samples'), (4, '16 samples'), (5, '32 samples'), (6, '64 samples')], default=5, help_text='Digital averaging filter level')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machine', models.ForeignKey(blank=True, help_text='Machine this gauge belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gauges', to='controller.machine')),
            ],
            options={
                'verbose_name': 'Gauge Configuration',
                'verbose_name_plural': 'Gauge Configurations',
            },
        ),
        migrations.CreateModel(
            name='FeatureInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Input label (A, B, C, ... Z, AA, AB, ...)', max_length=2)),
                ('channel_index', models.PositiveIntegerField(help_text='Hardware channel index (0-based)')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='measurement.feature')),
            ],
            options={
                'verbose_name': 'Feature Input',
                'verbose_name_plural': 'Feature Inputs',
                'ordering': ['feature', 'label'],
                'unique_together': {('feature', 'label')},
            },
        ),
        migrations.CreateModel(
            name='ChannelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_index', models.PositiveIntegerField(help_text='0-based channel index (matches hardware)')),
                ('name', models.CharField(help_text="Friendly name, e.g., 'OD Probe Left'", max_length=100)),
                ('enabled', models.BooleanField(default=True)),
                ('gauge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='measurement.gaugeconfig')),
            ],
            options={
                'verbose_name': 'Channel Configuration',
                'verbose_name_plural': 'Channel Configurations',
                'ordering': ['gauge', 'channel_index'],
                'unique_together': {('gauge', 'channel_index')},
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_values', models.JSONField(default=dict, help_text='Dict of channel_index: value')),
                ('computed_value', models.FloatField(help_text='Result after formula evaluation')),
                ('deviation', models.FloatField(help_text='Deviation from nominal (or value itself for LIMIT mode)')),
                ('in_tolerance', models.BooleanField()),
                ('in_warning', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=5)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', models.CharField(blank=True, help_text="Source identifier (e.g., 'N1700')", max_length=100)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='measurement.feature')),
            ],
            options={
                'verbose_name': 'Measurement',
                'verbose_name_plural': 'Measurements',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['feature', 'timestamp'], name='measurement_feature_59b840_idx'), models.Index(fields=['timestamp'], name='measurement_timesta_16a9fb_idx')],
            },
        ),
    ]
