# Generated by Django 6.0.3 on 2026-04-16 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
        ('tooling', '0002_toolinstance_tooltype_remove_toolassignment_tool_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='tool_type',
            field=models.ForeignKey(blank=True, help_text='Tool type that cuts this feature', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='features', to='tooling.tooltype'),
        ),
    ]
